name: build workflow
run-name: build workflow
on:
  push:
    branches:
      main
  pull_request:
    types:
      - opened
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test --passWithNoTests
      - name: Run build
        run: npm run build
      - name: Shared artefact workflow
        uses: actions/upload-artifact@v1
        with:
          name: hackaton-frontend-build
          path: build
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: hackaton-frontend-build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region : ${{ secrets.AWS_DEFAULT_REGION }} 
      - name: Deploy to S3
        run: aws s3 sync . s3://hackathon-fiap --acl public-read
        working-directory: hackaton-frontend-build